// We do not import the mdx files here inorder to make use of dynamic imports inside $postId file
export interface BlogList {
  slug: string;
  title: string;
  publishDate: string;
  description: string;
  pathName: string;
  readingTime: string;
  thumbnail: string;
}

export const blogList: Array<BlogList> = [
  {
    slug: "shopify-checkout-extension", // Filename
    title: "Shopify Checkout Upsell Extension",
    publishDate: "26 Apr 2025",
    description:
      "Every blog starts with a single post. This is yours. Make it great. Use it as a starting point for applying your own styles.",
    pathName: "/blog/shopify-checkout-extension",
    readingTime: "2 min",
    thumbnail: '/assets/images/casual-life-3d-meditation-crystal.webp'
  },
  {
    slug: "markdown-test",
    title: "Markdown Test Page",
    publishDate: "01 Dec 2021",
    description:
      "A sample page with the most common elements of an article, including headings, paragraphs, lists, and images..",
    pathName: "/blog/markdown-test",
    readingTime: "5 min",
    thumbnail: '/assets/images/casual-life-3d-workspace.webp'
  },
  {
    slug: "another-markdown",
    title: "Another Markdown",
    publishDate: "15 Dec 2021",
    description:
      " A sample page with the most common elements of an article, including headings, paragraphs, lists, and images. Generated by chatGPT.",
    pathName: "/blog/another-markdown",
    readingTime: "10 min",
    thumbnail: '/assets/images/casual-life-3d-likes.webp'
  },
];
